# fly.toml app configuration file generated for engageapp on 2024-01-28T11:02:58+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'engageapp'
primary_region = 'arn'

[build]
  image = 'kalyanchenu/engageapp:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dwwnkyi4m"
  CloudinarySettings__ApiKey="537313823255192"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
